# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20170314_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='req_id',
            new_name='reg_id',
        ),
    ]
