# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20170314_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='reg_id',
            field=models.CharField(max_length=200),
        ),
    ]
